openapi: 3.0.0
info:
  title: Books API
  description: A simple Books API using Node.js, Express, and TypeScript
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /books:
    get:
      summary: Get all books
      responses:
        200:
          description: A list of books
    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                author:
                  type: string
                publishedYear:
                  type: integer
      responses:
        201:
          description: Book added successfully
        400:
          description: Invalid input

  /books/{id}:
    get:
      summary: Get book by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Book details
        404:
          description: Book not found
    put:
      summary: Update an existing book
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                author:
                  type: string
                publishedYear:
                  type: integer
      responses:
        200:
          description: Book updated successfully
        400:
          description: Invalid input
        404:
          description: Book not found
    delete:
      summary: Delete a book by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Book deleted successfully
        404:
          description: Book not found
